const $=id=>document.getElementById(id);let state=null,tab='dashboard',busy=false;
const labels={mouse:'游標',click:'單擊',accel:'三軸加速度',touch:'觸控',hr:'心率',spo2:'血氧',battery:'電量',hr_auto:'內建心率排程',spo2_auto:'內建血氧排程',stress_auto:'內建壓力排程',hrv_auto:'內建 HRV 排程',stress:'壓力',glucose:'血糖',bp:'血壓',hrv:'HRV',temperature:'體溫',fatigue:'疲勞',composite:'綜合檢查',realtime_hr:'即時心率',capabilities:'能力位元'};
const text=(node,s)=>node.textContent=s,notice=s=>text($('notice'),s);
async function api(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.error||'操作失敗');return value}
async function action(fn){try{await fn();await refresh()}catch(e){notice(e.message)}}
async function switchTab(next){if(next===tab)return;await action(async()=>{await api('/api/options',{calibration:next==='calibration'});tab=next;document.querySelectorAll('.tab').forEach(el=>el.hidden=el.id!==tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('selected',el.dataset.tab===tab));if(tab==='calibration'&&$('calFrame').src.endsWith('about:blank'))$('calFrame').src='/calibration.html';render()})}
function render(){if(!state)return;const s=state;text($('connection'),s.connected?'已連線':s.message);$('connect').disabled=s.connected;$('disconnect').disabled=!s.connected;text($('name'),s.name);text($('hardware'),s.hardware||'硬體版本待讀取');text($('firmware'),s.firmware||'—');text($('serial'),s.serial?'序號：'+s.serial:'序號未提供');text($('battery'),s.battery===null?'—':`${s.battery}%`);text($('charging'),s.charging===null?'待讀取':s.charging?'充電中':'未充電');text($('autoStatus'),s.auto_status);text($('mouseStatus'),s.options.mouse?(s.paused?'已勾選，長按開始移動':'正在控制系統游標'):'尚未啟用');text($('calibrationStatus'),s.calibrated?'已有校正設定，啟用滑鼠會載入。':'請先完成中立、右、左、上、下校正。');
document.querySelectorAll('[data-option]').forEach(el=>{if(document.activeElement!==el)el.checked=!!s.options[el.dataset.option];el.disabled=!s.connected&&el.dataset.option!=='manage_auto'});$('healthInterval').value=String(s.options.health_interval);document.querySelectorAll('[data-read],[data-measure]').forEach(el=>el.disabled=!s.connected||s.active_measurement!==null);$('pause').disabled=!s.options.mouse;document.querySelectorAll('[data-probe]').forEach(el=>el.disabled=!s.connected||s.active_measurement!==null||el.dataset.probe==='7');$('readSelected').disabled=!s.connected;
text($('accelValue'),s.values.accel?s.values.accel.nominal_g.join(' / ')+' g':'—');text($('touchValue'),s.values.gesture?s.values.gesture.name:'—');text($('hrValue'),s.values.hr?(s.values.hr.display+' · '+s.values.hr.time.split('T')[1].slice(0,8)):'尚未量測');text($('spo2Value'),s.values.spo2?(s.values.spo2.display+' · '+s.values.spo2.time.split('T')[1].slice(0,8)):'尚未量測');
if(s.active_measurement)notice('量測中：'+({1:'心率',3:'血氧'}[s.active_measurement]||'候選項目')+'；游標暫停，最長 40 秒。');
if(tab==='explore'){if(!$('readQuery').options.length){for(const q of s.read_queries){const option=document.createElement('option');option.value=q.key;option.textContent=(labels[q.key]||q.key)+' · 0x'+q.opcode;$('readQuery').append(option)}}const evidence=$('evidence');evidence.replaceChildren();for(const [key,value]of Object.entries(s.evidence)){const p=document.createElement('p');p.textContent=`${labels[key]||key}：${value}`;evidence.append(p)}text($('gatt'),JSON.stringify({capability_bytes:s.capabilities,channels:s.channels,gatt:s.gatt},null,2));catalog()}
if(tab==='messages')logs();}
function catalog(){if(!state)return;const query=$('catalogSearch').value.toLowerCase(),root=$('catalog');root.replaceChildren();for(const item of state.catalog){if(query&&!JSON.stringify(item).toLowerCase().includes(query))continue;const row=document.createElement('div');row.className='catalog-row';const h=document.createElement('h3');h.textContent=`${item.channel} · 0x${item.opcode} ${item.type?'／類型 '+item.type:''} · ${item.name}`;const small=document.createElement('small');small.textContent=`${item.category} · ${item.provenance} · ${item.reference}`;row.append(h,small);if(item.dangerous){const label=document.createElement('span');label.className='status-tag';label.textContent='破壞性功能：本版不提供執行';row.append(label)}root.append(row)}}
function logs(){if(!state)return;const direction=$('logFilter').value,query=$('logSearch').value.toLowerCase();const root=$('logs'),bottom=root.scrollTop+root.clientHeight>=root.scrollHeight-50;root.replaceChildren();for(const row of state.logs){if(direction&&row.direction!==direction)continue;if(query&&!JSON.stringify(row).toLowerCase().includes(query))continue;const el=document.createElement('div');el.className='entry';const b=document.createElement('b');b.textContent=row.direction;const span=document.createElement('span');span.textContent=row.time.split('T')[1].slice(0,12)+' · '+JSON.stringify(Object.fromEntries(Object.entries(row).filter(([k])=>!['time','direction'].includes(k))));el.append(b,span);root.append(el)}if(bottom)root.scrollTop=root.scrollHeight}
async function refresh(){if(busy)return;busy=true;try{const r=await fetch('/api/state');if(!r.ok)throw Error('無法取得 App 狀態');state=await r.json();render()}catch(e){notice('服務尚未就緒：'+e.message)}finally{busy=false}}
$('connect').onclick=()=>action(async()=>{await api('/api/connect');notice('正在連接，讀取資訊與內建排程可能需要十多秒。')});$('disconnect').onclick=()=>action(()=>api('/api/disconnect'));$('pause').onclick=()=>action(()=>api('/api/pause'));$('calibrationLink').onclick=()=>switchTab('calibration');document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>switchTab(el.dataset.tab));document.querySelectorAll('[data-option]').forEach(el=>el.onchange=()=>action(()=>api('/api/options',{[el.dataset.option]:el.checked})));$('healthInterval').onchange=()=>action(()=>api('/api/options',{health_interval:Number($('healthInterval').value)}));document.querySelectorAll('[data-read]').forEach(el=>el.onclick=()=>action(()=>api('/api/read',{feature:el.dataset.read})));document.querySelectorAll('[data-measure]').forEach(el=>el.onclick=()=>action(()=>api('/api/measure',{type:Number(el.dataset.measure)})));
const candidateNames={2:'血壓',4:'疲勞',5:'綜合檢查',6:'即時心率',7:'心電圖',8:'壓力',9:'血糖',10:'HRV',11:'體溫'};for(const [type,name]of Object.entries(candidateNames)){const div=document.createElement('div');div.className='catalog-row';const label=document.createElement('span');label.textContent=name+' · 尚未驗證，未知數值不解讀 ';const b=document.createElement('button');b.textContent=Number(type)===7?'啟動流程未確認':'單次探測原始回應';b.disabled=Number(type)===7;b.dataset.probe=type;b.onclick=()=>action(()=>api('/api/measure',{type:Number(type)}));div.append(label,b);$('measureCandidates').append(div)}
$('inventory').onclick=()=>action(async()=>{for(const feature of ['capabilities','notification_routes','hr_auto','spo2_auto','stress_auto','hrv_auto','bp_auto','temperature_auto','today_activity']){notice('讀取中：'+(labels[feature]||feature));await api('/api/read',{feature});await refresh()}notice('基本能力與排程已讀取，請查看實機證據與收發訊息。')});$('catalogSearch').oninput=catalog;$('logFilter').onchange=logs;$('logSearch').oninput=logs;$('export').onclick=()=>{if(window.webkit?.messageHandlers?.nativeExport){window.webkit.messageHandlers.nativeExport.postMessage({})}else{const a=document.createElement('a');a.href='/api/export';a.download='qring-session.jsonl';a.click()}};
refresh();setInterval(refresh,1000);

$('access').onclick=()=>action(async()=>{const r=await api('/api/request-access');notice(r.allowed?'已取得控制權限。':'請在系統設定的「裝置控制和資料取用」開啟 QRing Studio 權限，再回來啟用滑鼠。')});

$('readSelected').onclick=()=>action(async()=>{const r=await api('/api/read',{feature:$('readQuery').value});notice((labels[r.feature]||r.feature)+'：'+r.status)});
