const $=id=>document.getElementById(id), unit=v=>{const n=Math.hypot(...v);if(n<.01)throw Error('資料無效');return v.map(x=>x/n)},dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
let socket,connected=false,samples=[],poses=[],step=0,capturing=false,profile=null,last=0,paused=false,position=[.5,.5],velocity=[0,0],saveDirty=true;
const local=['127.0.0.1','localhost'].includes(location.hostname);
function dual(p){const n=unit(p[0]),project=v=>{const g=unit(v),d=dot(g,n);return unit(g.map((x,i)=>x-d*n[i]))},r=project(p[1]),u=project(p[2]),c=dot(r,u),den=1-c*c;if(dot(unit(p[1]),n)>Math.cos(8*Math.PI/180)||dot(unit(p[2]),n)>Math.cos(8*Math.PI/180)||dot(unit(p[1]),n)<.5||dot(unit(p[2]),n)<.5)throw Error('傾斜幅度太小，請至少傾斜約 10 度。');if(den<.2)throw Error('向右與向上的姿勢太接近，請換一個方向重新校正。');return [n,r.map((x,i)=>(x-c*u[i])/den),u.map((x,i)=>(x-c*r[i])/den)];}
function message(s){$('message').textContent=s}
function update(){document.querySelectorAll('li').forEach((li,i)=>{li.className=i<poses.length?'done':i===step?'active':'';li.querySelector('b').textContent=i<poses.length?'已記錄':i===step&&connected?'目前步驟':'待校正'});$('capture').disabled=!connected||capturing||step>=3;$('capture').textContent=capturing?'記錄中…':['記錄中立姿勢','記錄向右姿勢','記錄向上姿勢'][step]||'方向校正完成';$('save').disabled=!profile||!connected||capturing;$('connect').disabled=connected||capturing;$('disconnect').disabled=!connected;$('status').className='badge'+(connected?' connected':'');$('status').textContent=connected?'R08 已連線':'尚未連線';}
function setStep(){const titles=['保持舒服的中立姿勢','傾斜到「向右」的姿勢','傾斜到「向上」的姿勢','試試你的新方向'];const texts=['讓手指放在你平常想停止游標的位置，靜止後按下記錄。','把戒指傾斜到你直覺想讓游標向右的姿勢，維持不動後記錄。','回到中立，再做出想讓游標向上的傾斜姿勢，維持不動後記錄。','慢慢傾斜手指，確認測試游標向右與向上移動。回到中立時應停止，再儲存。'];$('title').textContent=titles[step];$('instruction').textContent=texts[step];update()}
async function api(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error||'操作失敗');return result}
async function connect(){if(!local)return;try{$('connect').disabled=true;$('status').textContent='連接中…';await api('/api/connect');message('正在尋找戒指，請保持手機 QRing 斷線。')}catch(e){message(e.message);update()}}
function openSocket(){socket=new WebSocket(`ws://${location.host}/ws`);socket.onmessage=event=>{const d=JSON.parse(event.data);if(d.type==='status'){connected=d.connected;$('status').textContent=d.message||'';if(connected){setStep();message('連線成功，可以開始校正。')}else{velocity=[0,0];update();if(d.message)message(d.message)}}if(d.type==='accel'){const now=performance.now();last=now;const norm=Math.hypot(...d.raw)/8192;if(norm>=.8&&norm<=1.2)samples.push({time:now,v:unit(d.raw)});samples=samples.filter(s=>now-s.time<6000);$('xyz').textContent=d.raw.map(x=>(x/8192).toFixed(2)).join(' / ');$('fresh').textContent=norm>=.8&&norm<=1.2?'資料正常':'請減慢動作';const recent=samples.filter(s=>now-s.time<2000);$('hz').textContent=recent.length>2?`${((recent.length-1)*1000/(recent.at(-1).time-recent[0].time)).toFixed(1)} 筆／秒`:'量測中';if(profile&&norm>=.8&&norm<=1.2){const [n,r,u]=dual(profile.poses),g=unit(d.raw),den=dot(g,n);if(den<.5){velocity=[0,0];return}const sp=angle=>Math.sign(angle)*Number($('speed').value)*Math.pow(Math.max(0,Math.min(1,(Math.abs(angle)-8*Math.PI/180)/(27*Math.PI/180))),2);const target=[sp(Math.atan2(dot(g,r),den)),-sp(Math.atan2(dot(g,u),den))];velocity=velocity.map((x,i)=>x*.4+target[i]*.6)}else velocity=[0,0]}if(d.type==='gesture'&&d.code===4&&profile){paused=!paused;message(paused?'測試已暫停，長按可繼續。':'測試已恢復。')}};socket.onclose=()=>{connected=false;velocity=[0,0];update();message('本機服務已中斷。請重新開啟校正工具。');setTimeout(openSocket,2500)}}
async function capture(){if(!connected||capturing||step>=3)return;capturing=true;update();const began=performance.now();message('保持這個姿勢，不要移動手指…');const timer=setInterval(()=>$('progress').style.width=Math.min(100,(performance.now()-began)/30)+'%',100);await new Promise(r=>setTimeout(r,3000));clearInterval(timer);try{const ss=samples.filter(s=>s.time>=began&&s.time<=began+3000);if(!connected||ss.length<10||performance.now()-last>400)throw Error('資料不足，請確認戒指連線後再試。');const mean=ss[0].v.map((_,i)=>ss.reduce((a,s)=>a+s.v[i],0)/ss.length),spread=Math.max(...mean.map((m,i)=>Math.sqrt(ss.reduce((a,s)=>a+(s.v[i]-m)**2,0)/ss.length)));if(spread>.035)throw Error('手指還在移動，請保持姿勢靜止後重試。');const candidate=[...poses,unit(mean)];if(candidate.length===3)dual(candidate);poses=candidate;step=poses.length;if(step===3){profile={version:1,name:'R08_E703',poses,speed:Number($('speed').value)};saveDirty=true;$('padHint').textContent='傾斜移動 · 中立停止 · 長按暫停';position=[.5,.5];velocity=[0,0];message('三個姿勢已記錄，先確認方向再儲存。')}else message('姿勢記錄成功。')}catch(e){message(e.message)}finally{capturing=false;$('progress').style.width='0';setStep()}}
function reset(){if(capturing)return;poses=[];step=0;profile=null;velocity=[0,0];position=[.5,.5];paused=false;$('padHint').textContent='完成三個姿勢後，即可測試移動';message('校正已重置，已儲存的設定不會被刪除。');if(connected)setStep();else update()}
async function save(){try{if(!profile)throw Error('請先完成三個姿勢');profile.speed=Number($('speed').value);await api('/api/save',profile);saveDirty=false;message('已儲存到這台 Mac。下次啟動戒指滑鼠會使用這份校正。')}catch(e){message(e.message)}}
$('connect').onclick=connect;$('capture').onclick=capture;$('reset').onclick=reset;$('save').onclick=save;$('center').onclick=()=>{position=[.5,.5];velocity=[0,0]};$('speed').oninput=()=>{$('speedValue').textContent=$('speed').value;saveDirty=true};$('disconnect').onclick=async()=>{try{const result=await api('/api/disconnect');message(result.message)}catch(e){message(e.message)}};
let frame=performance.now();function animate(now){const dt=Math.min(.04,(now-frame)/1000);frame=now;const pad=$('pad');if(profile&&connected&&!paused&&now-last<350){position[0]=Math.max(.025,Math.min(.975,position[0]+velocity[0]*dt/pad.clientWidth));position[1]=Math.max(.035,Math.min(.965,position[1]+velocity[1]*dt/pad.clientHeight))}$('cursor').style.left=position[0]*100+'%';$('cursor').style.top=position[1]*100+'%';if(connected&&now-last>600)$('fresh').textContent='等待新資料';requestAnimationFrame(animate)}requestAnimationFrame(animate);
if(local){openSocket();fetch('/api/profile').then(r=>r.json()).then(d=>{if(d.profile)message('這台 Mac 已有儲存的設定，可重新校正取代。')}).catch(()=>message('本機服務尚未啟動。'))}else{$('connect').hidden=true;$('localLink').hidden=false;$('hostedNote').hidden=false;$('title').textContent='在你的 Mac 上完成校正';$('instruction').textContent='這個工具需要接收你手上的戒指資料。請開啟本機版本，依中立、向右、向上三個姿勢完成校正。';$('reset').disabled=true;$('speed').disabled=true;message('若本機版本無法開啟，請先啟動 Mac 上的校正工具。')}
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'get_calibration_status',description:'Read ring connection and calibration progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(input&&Object.keys(input).length)throw Error('No parameters allowed');return {connected,recordedPoses:poses.length,readyToSave:!!profile,paused,saved:!saveDirty}}})}
